version: '3'

volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - migrator-prod
    env_file:
      - prod.env
    environment:
      DB_HOST: pg-prod
    networks:
      - auth-service

  pg-local:
    image: postgres:14-alpine3.17
    env_file:
      - ".env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data
    networks:
      - auth-service

  pg-prod:
    image: postgres:14-alpine3.17
    env_file:
      - prod.env
    ports:
      - "54320:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data
    networks:
      - auth-service

  migrator-local:
    build:
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure
    depends_on:
      - pg-local
    env_file:
      - .env
    environment:
      DB_HOST: pg-local
    networks:
      - auth-service

  migrator-prod:
    build:
      context: .
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    env_file:
      - prod.env
    environment:
      DB_HOST: pg-prod
    networks:
      - auth-service

networks:
  auth-service:
    driver: bridge